config/routes.rb
Rails.application.routes.draw do
  root 'page#home'

  get 'page/result'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  end

  def result
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FbApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/page/home.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
	<meta charset="utf-8">
	<link rel="stylesheet" type="text/css" href="css/index1.css">
	<title>TBFBapp</title>

</head>

<body>
	<div class="main">
		<div class="content">
			<div class="TBlogo">

			</div>
			<div class="textbox">
				<h2>あなたにぴったりな<br>旅先を診断してみよう！</h2>

			</div>
			<div class="pushbutton">
        <p class="pushtext"><%= link_to "診断スタート",page_result_path,:style => "color: white;"%></p>
			</div>
		</div>
	</div>

</body>
</html>

app/views/page/result.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
	<meta charset="utf-8">
	<link rel="stylesheet" type="text/css" href="css/index1.css">
	<title>TBFBappresalt</title>
</head>
<body>
	<div class="main">
		<div class="content">
			<div class="TBlogo">

			</div>
			<div class="textbox">
				<h2>あなたの診断結果は・・・<br></h2>

			</div>
			<div class="pushbutton2">
				<a href="#"><p class="pushtext2">いいねをする</p></a>
			</div>
			<div class="pushbutton3">
				<a href="#"><p class="pushtext3">結果をシェアする</p></a>
			</div>
		</div>
	</div>

</body>
</html>